# Generated by Django 5.2.17 on 2026-08-25 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Kural kimliği küçük harf, rakam, _ ve - içerebilir.', regex='^[a-z0-9][a-z0-9_-]{0,63}$')])),
                ('enabled', models.BooleanField(default=True)),
                ('source_zone', models.CharField(choices=[('lan', 'LAN'), ('wan', 'WAN')], max_length=8)),
                ('destination_zone', models.CharField(choices=[('lan', 'LAN'), ('wan', 'WAN')], max_length=8)),
                ('source_cidr', models.CharField(max_length=18)),
                ('destination_cidr', models.CharField(max_length=18)),
                ('protocol', models.CharField(choices=[('any', 'Any'), ('icmp', 'ICMP'), ('tcp', 'TCP'), ('udp', 'UDP')], default='any', max_length=8)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('action', models.CharField(choices=[('accept', 'İzin ver'), ('drop', 'Engelle')], default='accept', max_length=8)),
                ('log', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
