# Generated by Django 5.2.17 on 2026-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policydeployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydeployment',
            name='operation',
            field=models.CharField(choices=[('apply', 'Uygulama'), ('rollback', 'Son işlemi geri alma')], max_length=16),
        ),
    ]
