# Generated by Django 5.2.17 on 2026-08-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_policydeployment_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydeployment',
            name='operation',
            field=models.CharField(choices=[('apply', 'Uygulama'), ('rollback', 'Son işlemi geri alma'), ('restore', 'Geçmiş sürüme dönme')], max_length=16),
        ),
    ]
